/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.sisloj;

import br.senai.sc.sisloj.views.CadastroCliente;
import br.senai.sc.sisloj.views.ListagemCliente;
import br.senai.sc.sisloj.views.PainelAmarelo;
import br.senai.sc.sisloj.views.PainelRosa;
import br.senai.sc.sisloj.views.TelaPadrao;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class SisLojFrame extends javax.swing.JFrame {

    /**
     * Creates new form SisLojFrame
     */
    public SisLojFrame() {
        initComponents();//metodo construtor
        
        PainelRosa pRosa = new PainelRosa();
        PainelAmarelo pAmarelo = new PainelAmarelo();
        CadastroCliente cadCli = new CadastroCliente();
        TelaPadrao tp = new TelaPadrao();
       
        
        painelPrincipal.add(cadCli, "CadastroCliente");  
        painelPrincipal.add(pRosa, "Painel Rosa");
        painelPrincipal.add(pAmarelo, "Painel Amarelo");
        painelPrincipal.add(tp, "Tela Padrao");
        
        
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "Tela Padrao");
        
        this.setExtendedState(MAXIMIZED_BOTH);// inicia a tela maximizada.
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        barradeMenu = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        cadastrarCliente = new javax.swing.JMenuItem();
        listarCliente = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        paineisColorido = new javax.swing.JMenu();
        painelRosa = new javax.swing.JMenuItem();
        painelAmarelo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 450));

        painelPrincipal.setLayout(new java.awt.CardLayout());

        menuCliente.setText("Cliente");
        menuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClienteActionPerformed(evt);
            }
        });

        cadastrarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        cadastrarCliente.setText("Cadastrar cliente");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(cadastrarCliente);

        listarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        listarCliente.setText("Listar cliente");
        listarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(listarCliente);

        barradeMenu.add(menuCliente);

        menuProduto.setText("Produto");

        jMenuItem2.setText("Cadastrar produto");
        menuProduto.add(jMenuItem2);

        jMenuItem4.setText("Listar produto");
        menuProduto.add(jMenuItem4);

        barradeMenu.add(menuProduto);

        paineisColorido.setText("Paineis Coloridos");

        painelRosa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        painelRosa.setText("Painel Rosa");
        painelRosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                painelRosaActionPerformed(evt);
            }
        });
        paineisColorido.add(painelRosa);

        painelAmarelo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        painelAmarelo.setText("Painel Amarelo");
        painelAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                painelAmareloActionPerformed(evt);
            }
        });
        paineisColorido.add(painelAmarelo);

        barradeMenu.add(paineisColorido);

        setJMenuBar(barradeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClienteActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "teste com atalho");
    }//GEN-LAST:event_menuClienteActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
       CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "CadastroCliente");
       
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void listarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarClienteActionPerformed
        // TODO add your handling code here:
         ListagemCliente lc = new ListagemCliente();
      painelPrincipal.add(lc, "Listar Cliente");
      
      CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "Listar Cliente");
    }//GEN-LAST:event_listarClienteActionPerformed

    private void painelRosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_painelRosaActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "Painel Rosa");
    }//GEN-LAST:event_painelRosaActionPerformed

    private void painelAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_painelAmareloActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "Painel Amarelo");
    }//GEN-LAST:event_painelAmareloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisLojFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SisLojFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barradeMenu;
    private javax.swing.JMenuItem cadastrarCliente;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem listarCliente;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu paineisColorido;
    private javax.swing.JMenuItem painelAmarelo;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JMenuItem painelRosa;
    // End of variables declaration//GEN-END:variables
}
